name: Conda Forge User CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: "cirun-openstack-cpu-medium--${{ github.run_id }}"
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo "Add other actions to build"
          echo "Hello"
